from typing import Dict, Any


class Config:
    theseus_dir: str
    config_file: str
    data_file: str
    config_defaults: Dict[str, Any]

    def __init__(self) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def _write_config(self) -> None: ...
    def _load_config(self) -> None: ...
    @staticmethod
    def dict_merge(dic1: Dict, dic2: Dict) -> Dict: ...


config: Config
