from twisted.internet.address import IPv4Address, IPv6Address

from typing import Union, Any


class ContactInfo:
    def __init__(self, host: Union[IPv4Address, IPv6Address], port: int, key) -> None: ...  # TODO what type should 'key' be? is it bytes?
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def asBytes(self) -> bytes: ...
