from typing import Dict


class TheseusProtocolError(Exception):
    errcode: int
    error_name: str

errcodes: Dict[int, TheseusProtocolError]
def errcode(cls: TheseusProtocolError) -> TheseusProtocolError: ...

class Error100(TheseusProtocolError): ...
class Error101(TheseusProtocolError): ...
class Error200(TheseusProtocolError): ...
class Error201(TheseusProtocolError): ...
class Error202(TheseusProtocolError): ...
class Error203(TheseusProtocolError): ...
class Error300(TheseusProtocolError): ...
class Error301(TheseusProtocolError): ...
class KRPCError(Exception): ...
class BencodeError(Exception): ...
class TheseusConnectionError(Exception): ...
